#!/usr/bin/env bash
#This script displays numbers from 1 to 100 but displays fizzbuzz if the number is a multiple of 3 and 5,also displays fizz and buzz if the number is a multiple of 3 and 5 respectively.
for ((i=1;i<=100;i++))
do 
	if ((i % 3 == 0)) && ((i % 5 == 0))
	then 
		echo "fizzbuzz"
	elif ((i % 3 == 0))
	then
		echo "fizz"
	elif ((i % 5 == 0))
	then
		echo "buzz"
	else 
		echo "$i"
	fi 
done	
