#!/usr/bin/env bash
#This script displays onlt the username,user id and the home directory path for the user of the file /etc/passwd
path="etc/passwd"
if [ -e $path ]
then
	while IFS=: read -r username _ userid _ _ home_directory _
	do
		echo "Username: $username"
		echo "User ID: $userid"
		echo "Home Directory: $home_directory"
		echo
	done < "$path"
else
	echo "The file $path does not exist"
fi	
