#!/usr/bin/env bash
#This script displays the visitor ip along with the http status code from the Apache log file
log_file="apache-access.log"
if [ -e $log_file ]
then
      awk '{print $1 , $9}' "$log_file"
else 
      echo "The log file $log_file does not exist"
fi
