#!/usr/bin/env bash
#This script displays Best school in all other iterations except for 4 and 8 where it displays bad luck and good luck respectively.
i=0
while [ $i -eq 10 ]
do 
  echo "Best School"
  i=$((i+1))
if [ $i -eq 4 ]
then 
  echo "bad luck"
elif [ $i -eq 8 ]
then 
   echo "good luck"
else 
     echo "Best School"
fi 
done
