#!/usr/bin/env bash
#This script displays information about the file school.
file="school"
if [ -e "$file" ] 
then
	echo "school file exists"
else 
	echo "school file does not exist"
if [ -s	$file ]
then
	echo "school file is not empty"
else 
	echo "school file is empty"
if [ -f $file ]
then
	echo "school is a regular file"
fi	
