#!/usr/bin/env bash
#This script stops the "to infinty and beyond" process using kill
PROGRAM="4-to_infinity_and_beyond"
PID="$(ps -ef | awk -v file="$PROGRAM" '$NF ~file {print $2}'| tail -n 1)"
kill -15 "$PID"
