#!/usr/bin/env bash
#This script displays "To infinity and beyond indefinitely with a 2 second interval between each iteration.It also displays "I am invincible" when receiving a SIGTERM signal.
while :                                            
do                                                 
        echo "To infinity and beyond"              
        sleep 2                                    
        trap 'echo "I am invincible!!!"' SIGTERM   
done
